config/routes.rb
Refinery::Core::Engine.routes.draw do

  # Admin routes
  namespace :menus do
    namespace :admin, :path => 'refinery' do
      resources :menu_links, only: [:create, :destroy]

      resources :menus do
        post :update_positions, :on => :collection
        resources :menu_links, :only => [:index, :show] do
          post :update_positions, :on => :collection
        end
      end
      
    end
  end
end

app/models/refinery/menus/menu_link.rb
module Refinery
  module Menus
    class MenuLink < Refinery::Core::BaseModel
      self.table_name = "refinery_menus_links"
      
      attr_accessible :parent_id, :refinery_page_id, :refinery_menu_id, :resource, :resource_id, :resource_type,
                      :title_attribute, :custom_url, :label, :menu, :id_attribute, :class_attribute

      belongs_to :menu, :class_name => '::Refinery::Menus::Menu', :foreign_key => :refinery_menu_id
      belongs_to :resource, :polymorphic => true

      # Docs for acts_as_nested_set https://github.com/collectiveidea/awesome_nested_set
      # rather than :delete_all we want :destroy
      acts_as_nested_set :dependent => :destroy

      validates :menu, :presence => true
      validates :label, :presence => true

      before_validation :set_label

      def self.find_all_of_type(type)
        # find all resources of the given type, determined by the configuration
        # TODO - we may want to allow configuration of conditions (DONE), ordering, etc
        if scope = self.resource_config(type)[:scope]
          scope.is_a?(Symbol) ? resource_klass(type).send(scope) : resource_klass(type).instance_eval(&scope)
        else
          resource_klass(type).all
        end
      end

      def self.resource_klass(type)
        resource_config(type)[:klass].constantize
      end

      def self.resource_config(type)
        Refinery::Menus.menu_resources[type.to_sym]
      end

      def set_label
        if label.blank?
          if custom_link?
            begin
              self.label = custom_url.match(/(\w+)\.\w+$/).captures.join.titleize
            rescue
              self.label = custom_url
            end
          else
            self.label = resource.send(resource_config[:title_attr])
          end
        end
      end

      def resource_klass
        Refinery::Menus::MenuLink.resource_klass(resource_type)
      end

      def resource_config
        Refinery::Menus::MenuLink.resource_config(resource_type)
      end

      def resource_type
        super || "Custom link"
      end

      def type_name
        resource_type.titleize
      end

      def custom_link?
        resource_id.nil? || resource_type.nil?
      end

      def resource_link?
        resource_id.present? && resource_type.present?
      end

      def resource
        return nil if custom_link?
        resource_klass.find(resource_id)
      end

      def resource_title
        resource.send(resource_config[:title_attr])
      end

      def title
        title_attribute.present? ? title_attribute : label
      end

      def resource_url
        resource.present? ? resource.url : '/'
      end

      def resource=(record)
        klass = record.class.base_class.name
        key = klass.underscore.tr!("-", "_")
        if Refinery::Menus.menu_resources.has_key?(key)
          super
          resource_type = key
        elsif type = Refinery::Menus.menu_resources.detect{|k,v| v.has_key?(:klass) && v[:klass] = klass}.first
          resource_type = type
        end
      end

      def url
        if custom_link?
          custom_url
        else
          resource_url
        end
      end

      def as_json(options={})
        json = super(options)
        if resource_link?
          json = {
            resource: {
              title: resource_title
            }
          }.merge(json)
        end
        json
      end

      def to_refinery_menu_item
        {
          :id => id,
          :lft => lft,
          :menu_match => menu_match,
          :parent_id => parent_id,
          :rgt => rgt,
          :title => label,
          :type => self.class.name,
          :url => url,
          :html => {
            :id => id_attribute,
            :class => class_attribute,
            :title => title
          }
        }
      end

    end
  end
end

app/controllers/refinery/menus/admin/menu_links_controller.rb
module Refinery
  module Menus
    module Admin
      class MenuLinksController < Refinery::AdminController

        def create
          respond_to do |format|
            format.js do
              @menu_links = []
              if params[:resource_ids]
                params[:resource_ids].each do |id|
                  @menu_links << MenuLink.create({resource_id: id}.merge(params[:menu_link]))
                end
              else
                @menu_links << MenuLink.create(params[:menu_link])
              end
            end
          end
        end

        def destroy
          respond_to do |format|
            format.js do
              @menu_link = MenuLink.find(params[:id])
              @menu_link.destroy
            end
          end
        end

      end
    end
  end
end

app/views/refinery/admin/menu_links/_custom_link.html.erb
<div class="field">
  <%= f.label :custom_url, t('.custom_url') %>
  <%= f.text_field :custom_url %>
</div>

<div class="field">
  <%= f.label :label %>
  <%= f.text_field :label %>
</div>

<% if Refinery::Menus.html_attributes %>
	<div class="field">
	  <%= f.label :title_attribute %>
	  <%= f.text_field :title_attribute %>
	</div>

  <div class="field">
    <%= f.label :id_attribute, t('id_attribute', :scope => 'refinery.admin.menu_links') %>
    <%= f.text_field :id_attribute %>
  </div>

  <div class="field">
    <%= f.label :class_attribute %>
    <%= f.text_field :class_attribute %>
  </div>
<% end %>

app/views/refinery/admin/menu_links/_menu_link.html.erb
<%= fields_for "menu[links_attributes][#{menu_link.id}]", menu_link do |f| %>
  <li class='pp-link clearfix record' id="<%= dom_id(menu_link)%>">
    <div class='header'>
      <div class='name'><%= menu_link.label %></div>
      <div class='type'><%= menu_link.type_name %></div>
      <span class='arrow'>&nbsp;</span>
    </div>
    <div class='body'>
      <%= f.hidden_field :id %>
      <% if f.object.custom_link? %>
        <%= render partial: "refinery/admin/menu_links/custom_link", object: menu_link, locals: {f: f} %>
      <% else %>
        <%= render partial: "refinery/admin/menu_links/resource_link", object: menu_link, locals: {f: f} %>
      <% end %>

      <%= link_to t('remove', :scope => 'refinery.admin.menu_links'), admin_menu_link_path(menu_link),
                  method: :delete,
                  remote: true,
                  class: 'remove' %>
    </div>

    <ul class='nested'>
      <% menu_link.children.each do |child|  %>
        <%= render partial: 'refinery/admin/menu_links/menu_link', object: child %>
      <% end %>
    </ul>
  </li>
<% end %>

app/views/refinery/admin/menu_links/_resource_link.html.erb
<div class="field">
  <%= f.label :label %>
  <%= f.text_field :label %>
</div>

<% if Refinery::Menus.html_attributes %>
	<div class="field">
	  <%= f.label :title_attribute %>
	  <%= f.text_field :title_attribute %>
	</div>

	<div class="field">
    <%= f.label :id_attribute, t('id_attribute', :scope => 'refinery.admin.menu_links') %>
    <%= f.text_field :id_attribute %>
  </div>

  <div class="field">
    <%= f.label :class_attribute %>
    <%= f.text_field :class_attribute %>
  </div>
<% end %>

<div class="field">
  <%= f.label :original %>
  <div class='original-resource'><%= resource_link.resource_title %></div>
</div>

app/views/refinery/admin/menu_links/_resource_link_editor_box.html.erb
<%= content_tag :div, class: "pp-add-box resource-pp-add-box" do %>
  <%= form_for [refinery, :admin, @menu.links.build(refinery_resource_type: resource_type)], remote: true do |f| %>
    <h3><%= resource_type.to_s.titleize %></h3>
    <div class='pp-selection-box'>
      <ul class='checkboxes'>
        <%= f.hidden_field :refinery_menu_id %>
        <%= f.hidden_field :refinery_resource_type %>

        <% resources = Refinery::MenuLink.find_all_of_type(resource_type) %>
        <% resources.each_with_index do |object, index| %>
          <li>
            <%= check_box_tag "refinery_resource_ids[]", object.id %>
            <%= label_tag "refinery_resource_ids[]", object.send(Refinery::MenuLink.resource_config(resource_type)[:title_attr]) %> 
          </li>
        <% end %>
      </ul>
    </div>
    <% # add resource type here %>
    <%= f.submit t('add', :scope => 'refinery.admin.menu_links', resource: resource_type.to_s.titleize)  %>
  <% end %>
<% end %>

app/views/refinery/admin/menu_links/create.js.erb
$('.pp-placeholder').remove();
reset_link_forms();
<% @menu_links.each do |menu_link| %>
	var partial = '<%= j render partial: "refinery/admin/menu_links/menu_link", object: menu_link %>'
	$('#sortable_list').append(partial);
<% end %>